repository:  
  name:  Learning-CPlusPlus-By-Reading-PPP2E
  description:  Documentation of my experiences learning to program in C++ by reading Bjarne Stroustrup's _Programming: Principles and Practice Using C++_, Second Edition. Stored as a literate programming record of how I work through the textbook's exercises in Markdown and C++ sources processed by zyedidia/Literate
